const {chromium}=require(process.env.TINYMAKER_PLAYWRIGHT || 'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..');
const meshFixture=process.env.TINYMAKER_MESHY_GLB;
if(!meshFixture){console.log('SKIP browser_artisan_quality: set TINYMAKER_MESHY_GLB to an existing Meshy GLB to run this optional fixture test.');process.exit(0);}
assert.ok(fs.existsSync(meshFixture),'TINYMAKER_MESHY_GLB does not exist');
fs.mkdirSync(path.join(root,'research/screenshots'),{recursive:true});fs.mkdirSync(path.join(root,'.cache'),{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_BIN || undefined,headless:true});
try{const c=await b.newContext({viewport:{width:1440,height:1100}}),p=await c.newPage(),errors=[],posts=[];
p.on('pageerror',e=>errors.push(e.message));
await p.route('**/*',r=>{if(r.request().method()!=='GET'){posts.push(r.request().url());return r.abort();}const u=new URL(r.request().url());if(u.hostname!=='127.0.0.1')return r.abort();if(u.pathname==='/api/status')return r.fulfill({json:{ok:true,firmwareVersion:'0.18.5',firmwareBuild:'local-ui-test',state:'Local preview',busy:false,receiving:false,webControl:false,freeHeap:170000,ip:'Preview only',layerText:'0 / 0',wifiText:'Local preview',sdReady:false,lastCrash:null}});return r.continue();});
await p.goto('http://127.0.0.1:8794/#create');
await p.locator('#kcBoard button').filter({hasText:/^A$/}).first().click();
await p.locator('#kcSteps [data-step="3"]').click();await p.locator('#kcLegendOn').uncheck();
assert.equal(await p.locator('#kcSculptHeight').inputValue(),'19');assert.equal(await p.locator('#kcMeshyDetail').inputValue(),'100000');
await p.locator('#kcFile').setInputFiles(meshFixture);
await p.waitForFunction(()=>document.querySelector('#kcProductStatus').textContent.includes('Ready to slice'),null,{timeout:30000});
const measuredBefore=await p.locator('#kcSculptMeasured').innerText();
await p.locator('.kcGenerationOptions summary').click();
await p.locator('#kcMeshyUltra').check();assert.equal(await p.locator('#kcSaveProduct').isEnabled(),true);assert.equal(await p.locator('#kcDownloadProduct').isEnabled(),false);
await p.locator('#kcMeshyUltra').uncheck();
await p.locator('.kcGenerationOptions summary').click();
await p.locator('#kcSculptFill').click();
await p.waitForFunction(()=>document.querySelector('#kcSculptHeight').value==='30'&&document.querySelector('#kcSculptMeasured').textContent.length>0);
await p.waitForTimeout(400);
const measuredAfter=await p.locator('#kcSculptMeasured').innerText();assert.notEqual(measuredBefore,measuredAfter);
await p.locator('#kcProductName').fill('QA — existing Meshy model, enlarged');await p.locator('#kcSaveProduct').click();
await p.waitForFunction(()=>/Ready to slice|Saved · needs attention/.test(document.querySelector('#kcProductStatus').textContent),null,{timeout:30000});
const savedState=await p.locator('#kcProductStatus').innerText();assert.match(savedState,/Ready to slice/);console.log('After Fill:',savedState);
const views=[];
await p.locator('#kcPose [data-pose="printed"]').click();
for(const v of ['front','side','back','bottom']){await p.locator('#kcInspect [data-view="'+v+'"]').click();
 assert.equal(await p.locator('#kcPose [data-pose="made"]').getAttribute('class'),'on');
 views.push(await p.locator('#kcTop').evaluate(e=>e.toDataURL()));}
assert.equal(new Set(views).size,4);
await p.locator('#kcInspect [data-view="perspective"]').click();
await p.screenshot({path:path.join(root,'research/screenshots/artisan-quality-controls-qa.png'),fullPage:true});
assert.deepEqual(errors,[]);assert.deepEqual(posts,[]);
const result={passed:true,isolatedBrowser:true,source:'Caller-supplied existing Meshy GLB, not a new generation',measuredBefore,measuredAfter,savedState,checks:['new defaults19mm/Fine','existingMeshy import assembles and saves','Ultra edit updates save state','Fill enlarges and new variant saves','all4namedviews differ and inspectMadeorientation'],browserErrors:errors,posts,printStarted:false,newGenerationStarted:false};
fs.writeFileSync(path.join(root,'.cache/browser-artisan-quality.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
